core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from core import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myapp/', include('myapp.urls', namespace='myapp')),
                  path('users/', include('users.urls', namespace='users')),
                  path('social-auth/', include('social_django.urls', namespace='social')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users import views
from users.views import RegisterView, VerifyEmailView

app_name = 'users'

urlpatterns = [
    path('login/', views.login_page, name='login_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('register/', RegisterView.as_view(), name='register_page'),
    path('email_page/', TemplateView.as_view(template_name='users/email_page.html'), name='email_page'),
    path('verify/', VerifyEmailView.as_view(), name='verify_email'),
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=True)
    verification_code = models.CharField(max_length=6, blank=True, null=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
import uuid

from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = CustomUser
        fields = ('email', 'phone_number', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Bu email allaqachon mavjud!")
        return email

    def save(self, commit=True):
        user = super().save(commit=False)
        user.verification_code = str(uuid.uuid4())
        user.is_active = False
        if commit:
            user.save()
        return user

users/views.py
from random import randint
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, TemplateView
from django.core.mail import EmailMessage
from django.conf import settings
from users.models import CustomUser
from .forms import CustomUserCreationForm

User = get_user_model()


def login_page(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, "Tizimga muvaffaqiyatli kirdingiz!")
                return redirect("myapp:index")
            else:
                messages.error(request, "Sizning emailingiz tasdiqlanmagan")
                return redirect('users:login_page')
        else:
            messages.error(request, "Email yoki parol noto‘g‘ri!")

    return render(request, 'users/login.html')



def logout_page(request):
    logout(request)
    return redirect("users:login_page")


class RegisterView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:email_page')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.verification_code = self.generate_verification_code()
        user.save()

        verification_code = user.verification_code
        mail_subject = 'Your Registration Verification Code'
        message = f'Hello {user.email},\n\nYour verification code is: {verification_code}'

        email = EmailMessage(
            mail_subject,
            message,
            settings.EMAIL_HOST_USER,
            [user.email],
        )
        email.send()

        return redirect(self.success_url)

    def generate_verification_code(self):
        return str(randint(100000, 999999))


class EmailPageView(TemplateView):
    template_name = 'users/email_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            user = self.request.user
            context['user'] = user
            context['verification_code'] = user.verification_code
        return context


class VerifyEmailView(View):
    def post(self, request):
        verification_code = request.POST.get('verification_code')

        try:
            user = CustomUser.objects.get(verification_code=verification_code)
            user.is_active = True
            user.verification_code = ''
            user.save()

            messages.success(request, "Your email has been successfully verified!")
            return redirect('myapp:index')

        except CustomUser.DoesNotExist:
            messages.error(request, "Invalid verification code!")
            return redirect('users:email_page')

users/templates/users/email_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Verification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f7fc;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .container {
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
            text-align: center;
        }
        h2 {
            color: #333;
            font-size: 24px;
            margin-bottom: 20px;
        }
        p {
            color: #777;
            font-size: 16px;
            margin-bottom: 20px;
        }
        label {
            font-size: 16px;
            color: #333;
            margin-bottom: 10px;
            display: block;
            text-align: left;
        }
        input[type="text"] {
            width: 100%;
            padding: 12px;
            font-size: 16px;
            margin-bottom: 20px;
            border: 1px solid #ddd;
            border-radius: 5px;
            outline: none;
        }
        input[type="text"]:focus {
            border-color: #007bff;
        }
        button {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 12px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            width: 100%;
        }
        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Email Verification</h2>
        <p>Please enter the verification code sent to your email.</p>
        <form method="POST" action="/users/verify/">
            {% csrf_token %}
            <label for="verification_code">Verification Code:</label>
            <input type="text" name="verification_code" required>
            <button type="submit">Verify</button>
        </form>
    </div>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base/base.html' %}
{% block title %} Login Page {% endblock %}

{% block login_content %}
    <main class="main" id="top">
        <div class="container-fluid">
            <div class="row min-vh-100 flex-center g-0">
                <div class="col-md-6">
                    <h3>Login</h3>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="alert alert-warning">{{ message }}</p>
                        {% endfor %}
                    {% endif %}

                    {% if form.errors %}
                        <ul class="alert alert-danger">
                            {% for field, errors in form.errors.items %}
                                <li>{{ field }}: {{ errors|striptags }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label">Email</label>
                            <input class="form-control" name="email" type="text" required/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Password</label>
                            <input class="form-control" name="password" type="password" required/>
                        </div>
                        <button class="btn btn-primary w-100" type="submit">Log in</button>
                    </form>

                    <div class="row g-2 mt-2">
                        <div class="col-sm-6"><a class="btn btn-outline-google-plus btn-sm d-block w-100" href="{% url "social:begin" "google-oauth2" %}"><span
                                class="fab fa-google-plus-g me-2" data-fa-transform="grow-8"></span>Google</a></div>
                        <div class="col-sm-6"><a class="btn btn-outline-google-plus btn-sm d-block w-100" href="{% url 'social:begin' 'github' %}"><span
                                class="fab fa-github-square me-2" data-fa-transform="grow-8"></span>GitHub</a>
                        </div>
                        <div class="col-sm-6"><a class="btn btn-outline-facebook btn-sm d-block w-100" href="{% url 'social:begin' 'facebook' %}"><span
                                class="fab fa-facebook-square me-2" data-fa-transform="grow-8"></span>Facebook</a>
                        </div>
                    </div>
                    <p class="mt-3">Hisobingiz yo‘qmi? <a href="{% url 'users:register_page' %}">Ro‘yxatdan o‘tish</a>
                    </p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base/base.html' %}
{% block title %} Register Page {% endblock %}

{% block register_content %}
    <main class="main" id="top">
        <div class="container-fluid">
            <div class="row min-vh-100 flex-center g-0">
                <div class="col-md-6">
                    <h3>Ro‘yxatdan o‘tish</h3>
                    {% if messages %}
                        {% for message in messages %}
                            <p class="alert alert-warning">{{ message }}</p>
                        {% endfor %}
                    {% endif %}

                    {% if form.errors %}
                        <ul class="alert alert-danger">
                            {% for field, errors in form.errors.items %}
                                <li>{{ field }}: {{ errors|striptags }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <form method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label">Email</label>
                            <input class="form-control" name="email" type="text" required/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Parol</label>
                            <input class="form-control" name="password1" type="password" required/>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Parolni tasdiqlang</label>
                            <input class="form-control" name="password2" type="password" required/>
                        </div>
                        <button class="btn btn-primary w-100" type="submit">Ro‘yxatdan o‘tish</button>
                    </form>

                    <p class="mt-3">Allaqachon hisobingiz bormi? <a href="{% url 'users:login_page' %}">Login</a></p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}